### PR TITLE
Add new indicators

### PR DESCRIPTION
**Pull request by priikone**
- ADX
- Aroon
- Bollinger bands
- Stochastic oscillator
- Williams %R

All indicators have tests.

Original code taken from Fojt's branch and refactored for the lastest
Techan master.

Signed-off-by: Pekka Riikonen <priikone@iki.fi>

### CODE REVIEW

**Comment by priikone** [comment]
Added also new indicator VWAP: https://github.com/priikone/techan.js/commit/ebdbb10c3bd381d56e693aeaa425be8bb69bdcb7

**Comment by andredumas** [comment]
@priikone @fojt Thanks for the contribution!

**Comment by thomashan** [comment]
Do we have any examples of ADX, Aroon, Bollinger bands, Stochastic oscillator, Williams %R, VMAP?
Maybe we can put examples of these advanced features into a separate example page??

**Comment by priikone** [comment]
I have intention to add more indicators and some other stuff soon.

**Pull request merged**
